# Uncomment the next line to define a global platform for your project
 	use_frameworks!
	platform :ios, '13.0'	
	project 'DIT355.xcodeproj'
	target 'DIT355' do
    	pod 'CocoaMQTT'
	pod 'SwiftyJSON', '~> 4.0'
end
